name: 'Release with Changelog'
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate changelog and create GitHub Release
        uses: fregante/release-with-changelog@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
